name: kodlingo
description: "Loopage - Oyunlaştırılmış Kodlama Öğrenme Platformu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0 # SDK sürümünü biraz esnetmek daha güvenlidir

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Temel Paketler
  http: ^1.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  
  # Yeni Eklenenler (Ses ve Firebase hazırlığı)
  audioplayers: ^6.0.0
  
  # --- FIREBASE SÜRÜMLERİNİ GÜNCELLEDİK ---
  # Bu sürümler birbiriyle ve yeni Flutter ile uyumludur
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # İsim değiştirme paketi
  change_app_package_name: ^1.1.0 

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/